# Generated by Django 3.2.18 on 2023-05-23 05:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('roleID', models.IntegerField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(5)])),
                ('password', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(8)])),
                ('nickname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('roleID', models.ForeignKey(db_column='roleID', on_delete=django.db.models.deletion.CASCADE, to='users.userroles')),
            ],
        ),
    ]
