# Generated by Django 3.2.18 on 2023-05-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='roleID',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
