# Generated by Django 4.1.7 on 2023-05-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='date',
        ),
    ]
