# Generated by Django 3.2.18 on 2023-05-24 04:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20230524_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWasteEntries',
            fields=[
                ('wasteEntryID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='roleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.userroles'),
        ),
        migrations.CreateModel(
            name='wasteItems',
            fields=[
                ('wasteItemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemDescription', models.CharField(max_length=64)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wasteEntryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.foodwasteentries')),
            ],
        ),
        migrations.AddField(
            model_name='foodwasteentries',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='audit.users'),
        ),
    ]
