# Generated by Django 4.1.7 on 2023-05-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_foodform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='userID',
            field=models.CharField(max_length=10),
        ),
    ]
