# Generated by Django 3.2.18 on 2023-05-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20230524_0439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodWasteEntries',
            new_name='WasteEntries',
        ),
        migrations.AlterModelOptions(
            name='userroles',
            options={'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterModelOptions(
            name='wasteentries',
            options={'verbose_name_plural': 'Waste Entries'},
        ),
        migrations.AlterModelOptions(
            name='wasteitems',
            options={'verbose_name_plural': 'Waste Items'},
        ),
    ]
