# Generated by Django 4.1.7 on 2023-05-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_donate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='type',
            new_name='orgtype',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
