# Generated by Django 4.1.7 on 2023-05-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_rename_type_organisation_orgtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgtype',
            field=models.CharField(max_length=90, null=True, verbose_name='Organisation Type'),
        ),
    ]
