# Generated by Django 4.1.7 on 2023-05-29 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_remove_donate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
