# Generated by Django 4.1.7 on 2023-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_donate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='id',
        ),
        migrations.AddField(
            model_name='donate',
            name='donateID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
