# Generated by Django 4.1.7 on 2023-05-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_remove_donate_id_donate_donateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='donateID',
        ),
        migrations.AddField(
            model_name='donate',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
