# Generated by Django 4.1.7 on 2023-05-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0010_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donate",
            name="amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="donate",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
