# Generated by Django 4.1.7 on 2023-05-31 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0012_delete_payment_alter_donate_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='roleID',
        ),
        migrations.AlterField(
            model_name='donate',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wasteentries',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
